model:
  renderer: 
    class_path: large_scene.VastGaussian.external.gsplat_appearance_renderer.GSplatAppearanceRenderer
  metric:
    class_path: large_scene.VastGaussian.external.appearance_modeling_metric.AppearanceModelingMetrics
