max_steps: 100000
model:
  gaussian:
    class_path: myimpl.models.scaffold_gaussian.ScaffoldLoDGaussian
  renderer:
    class_path: myimpl.renderers.scaffold_renderer.ScaffoldLoDRenderer
  metric:
    class_path: myimpl.metrics.scaffold_metrics.ScaffoldMetrics
  density:
    class_path: myimpl.density_controllers.scaffold_density_controller.ScaffoldDensityController
