data:
  path: datasets/MegaNeRF/sci-art/colmap
  parser:
    class_path: internal.dataparsers.colmap_dataparser.Colmap
    init_args:
      down_sample_factor: 4
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: datasets/MegaNeRF/sci-art/colmap/splits/val_images.txt
  train_max_num_images_to_cache: 256

model:
  gaussian:
    init_args:
      optimization:
        means_lr_init: 0.000064
        means_lr_scheduler:
          init_args:
            lr_final: 0.00000064
        scales_lr: 0.004
  density:
    init_args:
      densification_interval: 100