model:
  gaussian:
    class_path: internal.models.appearance_feature_gaussian.AppearanceFeatureGaussian
    init_args:
      sh_degree: 3
      appearance_feature_dims: 64
      optimization:
        appearance_feature_lr_init: 2e-3
  renderer: 
    class_path: large_scene.VastGaussian.external.gsplat_appearance_renderer.GSplatAppearanceRenderer
  metric:
    class_path: large_scene.VastGaussian.external.appearance_modeling_metric.AppearanceModelingMetrics
