max_steps: 30_000
data:
  batch_size: 1
  path: datasets/MegaNeRF/residence
  parser:
    class_path: myimpl.dataparsers.regularization_dataparser.Regularization
    init_args:
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: datasets/MegaNeRF/residence/splits/val_images.txt
      down_sample_factor: 4
      semantic_dir: extra/sam2_feature_dim32
  train_max_num_images_to_cache: 64
  num_workers: 4
  async_caching: true
model:
  renderer_output_types:
  - rgb
  - acc_depth
  - feature
  - pseudo_view
  gaussian:
    class_path: myimpl.models.grid_adapter_gaussian.LoDGridAdapterGaussian
    init_args:
      feature_adapter:
        dim_out: 32
        optimization:
          lr_init: 0.0
          lr_final: 0.0
      base_layer: 11
      max_level: 4
      start_level: 1
      optimization:
        means_lr_init: 0.0
        scales_lr: 5e-3
        rotations_lr_init: 1e-3
        offsets_lr_init: 1.6e-5
        offsets_lr_scheduler:
          init_args:
            lr_final: 1.6e-7
        anchor_features_lr: 2.5e-3
        opacity_mlp_lr_init: 2e-4
        opacity_mlp_lr_final: 2e-6
        cov_mlp_lr_init: 4e-4
        cov_mlp_lr_final: 4e-6
        color_mlp_lr_init: 8e-4
        color_mlp_lr_final: 5e-6
        feature_bank_mlp_lr_init: 1e-4
        feature_bank_mlp_lr_final: 1e-6
  renderer:
    class_path: myimpl.renderers.grid_renderer.GridGaussianRenderer
  metric:
    class_path: myimpl.metrics.scaffold_metrics.ScaffoldMetrics
    init_args:
      normal_from_iter: 0
      multiview_from_iter: 0
      lambda_multiview_feature: 0.1
      lambda_feature.init: 0.01
      lambda_feature.final_factor: 1.0
  density:
    class_path: myimpl.density_controllers.partition_grid_density_controller.PartitionGridGaussianDensityController
    init_args:
      densification: false
      # densify_until_iter: 15_000
      # densify_in_partition: false
      # prune_in_partition: false
      # densify_grad_threshold: 2e-4
save_iterations:
- 10_000
- 20_000
- 30_000