max_steps: 60_000
data:
  batch_size: 1

  # path: datasets/MipNeRF360/bicycle
  # parser:
  #   class_path: myimpl.dataparsers.regularization_dataparser.Regularization
  #   init_args:
  #     split_mode: experiment
  #     eval_image_select_mode: step
  #     eval_step: 8
  #     down_sample_factor: 4
  #     down_sample_rounding_mode: ceil
  #     semantic_dir: extra/sam2_feature_dim32

  path: datasets/MegaNeRF/residence
  parser:
    class_path: myimpl.dataparsers.regularization_dataparser.Regularization
    init_args:
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: datasets/MegaNeRF/residence/splits/val_images.txt
      down_sample_factor: 4

  train_max_num_images_to_cache: 64
  num_workers: 4
  async_caching: true
model:
  renderer_output_types:
  - rgb
  - acc_depth
  gaussian:
    class_path: myimpl.models.hash_grid_assisted_gaussian.HashGridAssistedGaussian
    init_args:
      feature_dim: 32
      base_layer: 11
      max_level: 4
      start_level: 1

      feature_fusion:
        # fix_hash_weight: true
        optimization:
          lr_init: 3e-5
          lr_final: 3e-5

      hash_grid_feature:
        out_dim: 32
        num_levels: 10
        min_res: 16
        max_res: 8192
        log2_hashmap_size: 16
        features_per_level: 4
        use_mixed: false

      optimization:
        hash_feature_lr_init: 0.0
        hash_feature_lr_final: 0.0
        anchor_features_lr: 5e-4
        anchor_features_lr_scheduler:
          warmup_steps: 0
        means_lr_init: 0.0
        scales_lr: 1e-3
        rotations_lr_init: 2e-4
        offsets_lr_init: 8e-5
        offsets_lr_scheduler:
          init_args:
            lr_final: 8e-7
        opacity_mlp_lr_init: 2e-4
        opacity_mlp_lr_final: 2e-5
        cov_mlp_lr_init: 4e-4
        cov_mlp_lr_final: 4e-5
        color_mlp_lr_init: 8e-4
        color_mlp_lr_final: 5e-5
        feature_bank_mlp_lr_init: 1e-4
        feature_bank_mlp_lr_final: 1e-5
  renderer:
    class_path: myimpl.renderers.hash_grid_assisted_renderer.HashGridAssistedGaussianRenderer
  metric:
    class_path: myimpl.metrics.scaffold_metrics.ScaffoldMetrics
    init_args:
      normal_from_iter: 0
      lambda_feature:
        enabled: false
  density:
    class_path: myimpl.density_controllers.grid_density_controllers.HashGridGaussianDensityController
    init_args:
      densify_until_iter: 40_000
      densify_grad_threshold: 1.2e-4
      scatter_mode: mean
      # densify_in_partition: true
      # prune_in_partition: true
save_iterations:
- 20_000
- 40_000
- 60_000